# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZWhyx8FRePiynxOw21qvi-hI5TJ6tygA
"""


import pandas as pd
import joblib
import os


model = joblib.load('model.pkl')
le_group = joblib.load('le_group.pkl')
le_cat = joblib.load('le_cat.pkl')

def predict_patient(df):
    preds = model.predict(df)
    risk_group_probs = preds[0]
    risk_cat_probs = preds[1]

    risk_group_class = risk_group_probs.argmax(axis=1)[0]
    risk_cat_class = risk_cat_probs.argmax(axis=1)[0]

    risk_group_label = le_group.inverse_transform([risk_group_class])[0]
    risk_cat_label = le_cat.inverse_transform([risk_cat_class])[0]
    return risk_group_label, risk_cat_label




